### ISSUE TITLE
Dependency unavailable

### ISSUE THREAD

**Issue by abbyslab** [thags/lingqAnkiSync#28]
Hi, I added the add-on via the normal mechanism and restarted anki. It's the only add-on I have.
```
When loading '⁨Lingq Anki Sync⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/home/abby/.var/app/net.ankiweb.Anki/data/Anki2/addons21/594879777/__init__.py", line 1, in <module>
    from .popUpWindow import UI
  File "/home/abby/.var/app/net.ankiweb.Anki/data/Anki2/addons21/594879777/popUpWindow.py", line 6, in <module>
    from .UIActionHandler import ActionHandler
  File "/home/abby/.var/app/net.ankiweb.Anki/data/Anki2/addons21/594879777/UIActionHandler.py", line 1, in <module>
    from .Converter import ConvertAnkiCardsToLingqs, ConvertLingqsToAnkiCards
  File "/home/abby/.var/app/net.ankiweb.Anki/data/Anki2/addons21/594879777/Converter.py", line 4, in <module>
    from Models.Lingq import Lingq
ModuleNotFoundError: No module named 'Models'
```
⁩My system info is:
```
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=2    
```
Anki was installed via flatpak.
I've looked into this directory "/.../net.ankiweb.Anki/.../594879777/" and ./Models/ and it's .py files on your github exist there.

**Comment by thags** [comment]
What distro of Linux do you run? I can try to reproduce and troubleshoot.

**Comment by abbyslab** [comment]
It's on Linux Mint 21.1 Cinnamon. Thanks.

**Comment by thags** [comment]
I found a temporary fix. 

I am not sure how long ankiweb takes to update the file, but I uploaded the new version there. If you want to use the addon sooner then you can modify the converter.py file to be the same as: https://github.com/thags/lingqAnkiSync/blob/main/LingqAnkiSync/Converter.py

The only changes where in the first 13 lines. 

Detailed info:
I think the sys.path.append or the os.path.realpath/os.path.dirname works differently on linux as it does on windows. 
I have this implemented so I can create tests for this without using relative imports, but relative imports work more reliably. 

Future plans:
Test if sys.path or os.path work differently between windows/linux and if there is a better way I can handle this import while maintaining testing.

**Comment by abbyslab** [comment]
Thank you, this fixed it for me :)
